[project]
name = "3dcp"
version = "0.1.0"
description = "A comprehensive citation network graph on the state of the art in 3D concrete printing"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.0",
    "pytest>=7.0.0",
]
